name: Deno CI Check

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "**.ts"
      - "deno.json"
      - ".github/workflows/deno-ci-check.yml"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Deno
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        with:
          deno-version: lts

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Type check
        run: deno check baseline-mcp-server.ts

      - name: Run tests
        run: deno test -A
